### PR TITLE
When using the liveReloadBaseUrl with an absolute URL, the non-path portion should be stripped when setting up middleware.

### PR DESCRIPTION
**Pull request by lukemelia**

### CODE REVIEW

**Comment by machty** [comment]
Plus. One.

**Comment by kevinwmerritt** [comment]
Any chance this will get merged?

**Comment by jbescoyez** [comment]
This PR fixes a regression mentioned in #38. The only workaround I found so far is to use an old version of `ember-cli-inject-live-reload`. It would be great to see this merged. /ping @rwjblue

**Comment by rwjblue** [comment]
Very sorry for the long delay here. Sorry for letting this fall through the cracks.

**Comment by lukemelia** [comment]
Better late than never @rwjblue! Thanks! 🍻

**Comment by jbescoyez** [comment]
Yeah! Thanks @rwjblue.

**Pull request merged**
