### PR TITLE
add cspNonce option to add a nonce attribute to the <script>

### PR DESCRIPTION
**Pull request by eturino**
for CSP compliance options.

This will allow using strict CSP in development using `script-dynamic` and a nonce.

### CODE REVIEW

**Comment by eturino** [comment]
@rwjblue could you have a look, please? :)

**Comment by sandstrom** [comment]
@eturino @rwjblue I see two alternatives here:

1. Solve this only for development. In that case, the solution could live here.
2. Solve this in [ember-cli-content-security-policy](https://github.com/rwjblue/ember-cli-content-security-policy). In that case, we need to consider minification, which will alter the script, and calculate the hash at a late stage. I think any effort is better spent here, but it's slightly more complicated.

More details around the second option here: https://github.com/rwjblue/ember-cli-content-security-policy/issues/67

**Comment by eturino** [comment]
I intended this only for development, to be honest.

**Comment by sandstrom** [comment]
For your own fork the code in this PR works well, so feel free to use it for local development!

However, due to the aforementioned reasons (my and rwjblues comments) I'm not sure it's a good idea to merge this PR in its current state.

**Comment by eturino** [comment]
fair enough :)

**Comment by sandstrom** [comment]
@eturino I still agree with you that CSP nonce support would be great (I want it myself), but I think it's better to make something that'll work for both production and development.

For that, https://github.com/rwjblue/ember-cli-content-security-policy/issues/67 is probably a good way to start. If you want to dig in I'm happy to provide some pointers on where to start! 😄

**Pull request closed without merging**
